Repository mangaki/mangaki, pull requests merged in 2018-09, with the labels that each got.

#619 CircleCI 2 — deployment to beta
  .circleci/config.yml
  provisioning/docker/Dockerfile
Labels: PR: Please Merge Now

#608 Bump requirements
  mangaki/setup.py
  requirements/production.txt
Labels: PR: To Review, good first PR

#611 Add migration file
  mangaki/mangaki/migrations/0095_auto_20180826_1148.py
Labels: PR: To Review, good first PR

#615 Improve SuggestionAdmin and WorkClusterAdmin
  mangaki/mangaki/admin.py
Labels: PR: To Review, good first PR

#621 Externalize recommendation algorithms
  .circleci/config.yml
  mangaki/mangaki/algo/__init__.py
  mangaki/mangaki/algo/als.py
  mangaki/mangaki/algo/als2.py
  mangaki/mangaki/algo/als3.py
  mangaki/mangaki/algo/balse.py
  mangaki/mangaki/algo/cfm.py
  mangaki/mangaki/algo/dataset.py
  mangaki/mangaki/algo/efa.py
  mangaki/mangaki/algo/fit_algo.py
  mangaki/mangaki/algo/fma.py
  mangaki/mangaki/algo/gbr.py
  mangaki/mangaki/algo/knn.py
  mangaki/mangaki/algo/knn2.py
  mangaki/mangaki/algo/knn_sample.py
  mangaki/mangaki/algo/lasso.py
  mangaki/mangaki/algo/lasso_sample.py
  mangaki/mangaki/algo/nmf.py
  mangaki/mangaki/algo/pca.py
  mangaki/mangaki/algo/recommendation_algorithm.py
  mangaki/mangaki/algo/sgd.py
  mangaki/mangaki/algo/sgd_sample.py
  mangaki/mangaki/algo/side.py
  mangaki/mangaki/algo/ssvd.py
  mangaki/mangaki/algo/svd.py
  mangaki/mangaki/algo/wals.py
  mangaki/mangaki/algo/xals.py
  mangaki/mangaki/algo/zero.py
  mangaki/mangaki/apps.py
  mangaki/mangaki/management/commands/compare.py
  mangaki/mangaki/management/commands/dedupe.py
  mangaki/mangaki/management/commands/fit_algo.py
  mangaki/mangaki/management/commands/morphing.py
  mangaki/mangaki/management/commands/poster_neighbors.py
  mangaki/mangaki/management/commands/unzip_algo.py
  mangaki/mangaki/settings.py
  mangaki/mangaki/tests/test_algo.py
  mangaki/mangaki/tests/test_mgt_commands.py
  mangaki/mangaki/tests/test_reco.py
  mangaki/mangaki/urls.py
  mangaki/mangaki/utils/dpp.py
  mangaki/mangaki/utils/fit_algo.py
  mangaki/mangaki/utils/profile.py
  mangaki/mangaki/utils/recommendations.py
  mangaki/mangaki/utils/stats.py
  mangaki/mangaki/views.py
  mangaki/setup.py
  requirements/dev.txt
  requirements/production.txt
Labels: PR: To Review

#617 Test: Filter WorkList by user watchlist
  mangaki/mangaki/views.py
Labels: PR: To Review

#612 Add link to work in card and translate category even in mosaic
  mangaki/mangaki/api/cards.py
  mangaki/mangaki/static/css/skin.css
  mangaki/mangaki/static/js/vote.js
  mangaki/mangaki/templates/mangaki/work_rating.html
Labels: PR: To Review

#630 Fix profile ordering
  mangaki/mangaki/utils/profile.py
  mangaki/mangaki/utils/recommendations.py
Labels: bugfix, good first PR

#631 Bump Bootstrap 4
  mangaki/mangaki/choices.py
  mangaki/mangaki/settings.py
  mangaki/mangaki/static/css/bootstrap.min.css
  mangaki/mangaki/static/css/glyphicons.css
  mangaki/mangaki/static/css/skin.css
  mangaki/mangaki/static/img/mangakiwhite.png
  mangaki/mangaki/static/js/bootstrap.min.js
  mangaki/mangaki/static/js/popper.min.js
  mangaki/mangaki/static/js/tooltip.js
  mangaki/mangaki/static/js/vote.js
  mangaki/mangaki/templates/account/account_deleted.html
  mangaki/mangaki/templates/account/login.html
  mangaki/mangaki/templates/account/password_reset.html
  mangaki/mangaki/templates/account/password_reset_from_key.html
  mangaki/mangaki/templates/account/signup.html
  mangaki/mangaki/templates/base.html
  mangaki/mangaki/templates/fix/fix_index.html
  mangaki/mangaki/templates/index.html
  mangaki/mangaki/templates/mangaki/artist_detail.html
  mangaki/mangaki/templates/mangaki/artist_list.html
  mangaki/mangaki/templates/mangaki/reco_list.html
  mangaki/mangaki/templates/mangaki/reco_list_dpp.html
  mangaki/mangaki/templates/mangaki/work_detail.html
  mangaki/mangaki/templates/mangaki/work_list.html
  mangaki/mangaki/templates/pagination.html
  mangaki/mangaki/templates/profile.html
  mangaki/mangaki/templates/profile_preferences.html
  mangaki/mangaki/templates/profile_reco.html
  mangaki/mangaki/templates/profile_work.html
  mangaki/mangaki/templates/profile_works.html
  mangaki/mangaki/templates/search.html
  mangaki/mangaki/templates/socialaccount/signup.html
  mangaki/mangaki/templates/works.html
  mangaki/mangaki/views.py
  mangaki/setup.py
  requirements/production.txt
Labels: PR: To Review, frontend, il marche sur l'eau !
