Repository mangaki/mangaki, pull requests merged in 2022-09, with the labels that each got.

#779 Add dev dependencies and fix tests for Python 3.10
  mangaki/mangaki/tests/test_mgt_commands.py
  poetry.lock
  pyproject.toml
Labels: ongoing, complex

#784 fix: drop Jupyter development dependency and fix Nix packaging
  flake.lock
  flake.nix
  nix/pkgs/mangaki/poetry-standard-overlay.nix
  poetry.lock
  pyproject.toml
Labels: complex

#783 Add Manami and Union-Find references
  mangaki/mangaki/management/commands/add_new_works.py
  mangaki/mangaki/tests/test_mgt_commands.py
  mangaki/mangaki/utils/manami.py
  mangaki/tests/data/manami/anime-offline-database.json
  mangaki/tests/data/manami/dead-entries/anidb.json
  mangaki/tests/data/manami/dead-entries/myanimelist.json
  mangaki/tests/data/manami_clusters.json
Labels: PR: To Review, il marche sur l'eau !
